---
title: "Submission Scoreboard"
output:
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
library(ProjectTemplate)
load.project()
```

```{r read_data, include=FALSE}
TEAMID = 167382

# Load the scoreboard data
SCOREBOARD = read.csv("raw/restaurant-revenue-prediction_public_leaderboard.csv",
                      stringsAsFactors=FALSE) %>%
  tbl_df %>%
  mutate_each(funs(ymd_hms), SubmissionDate) %>%
  mutate_each(funs(factor), TeamId, TeamName) %>%
  group_by(TeamId, TeamName, SubmissionDate) %>%
  summarize(Score = min(Score)) %>%
  mutate(
    us = TeamId == TEAMID
  )

FINAL_SCOREBOARD = SCOREBOARD %>% 
  group_by(TeamId, TeamName) %>% 
  summarize(
    FinalScore = min(Score),
    us = any(us)
  )

RESULTS = readHTMLTable("raw/private_leaderboard.html", header=TRUE, which=1, stringsAsFactors=FALSE)
colnames(RESULTS) = c("rank", "deltarank", "TeamName", "Score", "Entries", "LastSubmissionDate")
RESULTS %<>%
  mutate_each(funs(as.numeric), rank, Score) %>% 
  mutate_each(funs(factor), TeamName)

```

```{r scoreboard_best}
SCOREBOARD %>% 
  ggplot(aes(SubmissionDate, Score)) +
    geom_point(data = filter(SCOREBOARD, Score < 1.05*median(FINAL_SCOREBOARD$FinalScore), Score > 1e6, !us), aes(SubmissionDate, Score), color="grey") +
    geom_point(data = filter(SCOREBOARD, us), aes(SubmissionDate, Score), color="red") +
  #   geom_point(data = filter(SCOREBOARD, !us, Score<median(Score)), aes(SubmissionDate, Score), color="grey") +
  #   geom_point(data = filter(SCOREBOARD, us), aes(SubmissionDate, Score), color="red") +
    geom_hline(yintercept=median(FINAL_SCOREBOARD$FinalScore)) +
    xlab("Date") +
    ylab("Minimum RMSE (log) on Day") +
    scale_y_log10() +
    theme_bw() +
    ggtitle("Kaggle RRP: RMSE Scoreboard (scores less than median)")
```

```{r scoreboard_cdf}
PRESULTS = RESULTS %>%
  mutate(
    ppdiff = (1 - (Score / min(Score))) * -100
  )

usppdiff = (1 - ( 1829191.19517 / min(PRESULTS$Score))) * -100

ggplot(PRESULTS, aes(ppdiff)) +
  stat_ecdf() +
  geom_vline(xintercept=usppdiff, color="red") +
  geom_hline(yintercept=0) +
  geom_hline(yintercept=0.5, color="grey") +
  geom_text(aes(usppdiff, 0), label=sprintf("Our team: %0.2f %%", usppdiff), vjust=-1) +
  scale_x_reverse(lim=c(100, 0)) +
  theme_bw() +
  xlab("Percentage points off of minimum RMSE score") +
  ylab("Percentage of teams with worse score") +
  ggtitle("Random Deforestation: Restaurant Revenue Prediction")
```